Repository redhat-developer/devconsole-api, pull requests merged in 2019-04, with the labels that each got.

#20 Add failure reason to both GitSource and GitSourceAnalysis CRDs
  pkg/apis/devconsole/v1alpha1/gitsource_types.go
  pkg/apis/devconsole/v1alpha1/gitsourceanalysis_types.go
Labels: approved, lgtm, size/M

#21 adding git committer info to dockerfile to fix failing ci
  Dockerfile
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#19 adding annotations
  pkg/apis/devconsole/v1alpha1/component_types_annotations.go
Labels: approved, ok-to-test

#22 use buildtype if name is not present
  pkg/apis/devconsole/v1alpha1/component_types_labels.go
Labels: approved, size/XS
